# Generated by Django 4.2.5 on 2025-08-17 21:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):


    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokerBoard',
            fields=[
                ('pokerid', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=125, validators=[django.core.validators.MinLengthValidator(3)])),
                ('game_description', models.TextField(validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='pokermember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[[0, 'Spectator'], [1, 'Developer'], [2, 'Guest'], [3, 'Manager']], default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_membership', to=settings.AUTH_USER_MODEL)),
                ('poker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecreation.pokerboard')),
            ],
            options={
                'unique_together': {('poker', 'member')},
            },
        ),
        migrations.AddField(
            model_name='pokerboard',
            name='member',
            field=models.ManyToManyField(related_name='poker', through='gamecreation.pokermember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pokermember',
            name='poker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokerboard_membership', to='gamecreation.pokerboard'),
        ),
    ]
