# Generated by Django 4.2.5 on 2025-08-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecreation', '0001_initial_squashed_0006_alter_pokermember_poker'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokermember',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
