# Generated by Django 4.2.5 on 2025-08-17 21:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ticket', '0001_initial'), ('ticket', '0002_estimate'), ('ticket', '0003_alter_estimate_estimate'), ('ticket', '0004_estimate_estimate_date')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamecreation', '0005_rename_manager_pokerboard_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=125)),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('type', models.CharField(choices=[[0, 'task'], [1, 'bug'], [2, 'epic'], [3, 'story'], [4, 'subtask']], default=0)),
                ('Timer', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('finalEstimate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('pokerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_membership', to='gamecreation.pokerboard')),
            ],
        ),
        migrations.CreateModel(
            name='estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_ref', to='ticket.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_membership', to=settings.AUTH_USER_MODEL)),
                ('estimate_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
