# Generated by Django 5.2.5 on 2025-08-26 20:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ticket', '0001_initial_squashed_0004_estimate_estimate_date'), ('ticket', '0005_ticket_import_type_ticket_ticket'), ('ticket', '0006_alter_estimate_estimate_alter_ticket_timer_and_more'), ('ticket', '0007_ticket_key'), ('ticket', '0008_ticket_priority')]

    dependencies = [
        ('gamecreation', '0005_rename_manager_pokerboard_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=125)),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('type', models.CharField(choices=[(0, 'task'), (1, 'bug'), (2, 'epic'), (3, 'story'), (4, 'subtask')], default=0)),
                ('Timer', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('finalEstimate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('pokerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_membership', to='gamecreation.pokerboard')),
                ('import_type', models.CharField(choices=[(0, 'ticketId'), (1, 'sprintId'), (2, 'jql')], default=0)),
                ('ticket', models.CharField(blank=True, max_length=125, null=True)),
                ('key', models.CharField(default='SPP-1', max_length=125)),
                ('priority', models.CharField(default='Medium', max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_ref', to='ticket.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_membership', to=settings.AUTH_USER_MODEL)),
                ('estimate_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
