# Generated by Django 4.2.5 on 2025-08-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial_squashed_0004_estimate_estimate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='import_type',
            field=models.CharField(choices=[[0, 'ticketId'], [1, 'sprintId'], [2, 'jql']], default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
