# Generated by Django 4.2.5 on 2025-08-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_alter_estimate_estimate_alter_ticket_timer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='key',
            field=models.CharField(default='SPP-1', max_length=125),
        ),
    ]
