# Generated by Django 4.2.5 on 2025-08-12 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamecreation', '0005_rename_manager_pokerboard_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.EmailField(max_length=254)),
                ('accept', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
                ('pokerboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='gamecreation.pokerboard')),
            ],
        ),
    ]
