# Generated by Django 5.2.5 on 2025-08-26 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('Invite', '0001_initial'), ('Invite', '0002_invite_role'), ('Invite', '0003_alter_invite_table')]

    dependencies = [
        ('gamecreation', '0005_rename_manager_pokerboard_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.EmailField(max_length=254)),
                ('accept', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
                ('pokerboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='gamecreation.pokerboard')),
                ('role', models.IntegerField(choices=[(0, 'Spectator'), (1, 'Developer'), (2, 'Guest'), (3, 'Manager')], default=0)),
            ],
            options={
                'db_table': 'invite_invite',
            },
        ),
    ]
