# Generated by Django 4.2.5 on 2025-08-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='role',
            field=models.IntegerField(choices=[[0, 'Spectator'], [1, 'Developer'], [2, 'Guest'], [3, 'Manager']], default=0),
        ),
    ]
