# Generated by Django 4.2.5 on 2025-08-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invite', '0002_invite_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invite',
            table='invite_invite',
        ),
    ]
