# Generated by Django 5.2.5 on 2025-08-26 12:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api_keys', '0001_initial'), ('api_keys', '0002_alter_apikeys_apikey')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('cloudsite', models.CharField(max_length=125, validators=[django.core.validators.MinLengthValidator(10)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
