# Generated by Django 4.2.5 on 2025-08-11 18:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(max_length=125, validators=[django.core.validators.MinLengthValidator(20)])),
                ('cloudsite', models.CharField(max_length=125, validators=[django.core.validators.MinLengthValidator(10)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
