# Generated by Django 5.2.5 on 2025-08-30 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api_keys', '0001_initial_squashed_0002_alter_apikeys_apikey'), ('api_keys', '0003_alter_apikeys_apikey_alter_apikeys_cloudsite_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(max_length=256)),
                ('cloudsite', models.CharField(max_length=125)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userkey_membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
