# Generated by Django 4.2.5 on 2025-08-19 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeys',
            name='apikey',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20)]),
        ),
    ]
